apiVersion: config.engineersdaybook.dev/v1alpha1
kind: SopsSecret
metadata:
  name: github-upstream
  namespace: agentgateway-system
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ../../../functions/sops-secret/sops-secret
data:
  file: .env.secrets.json
  keys:
    Authorization: GITHUB_TOKEN
