---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
  namespace: cnpg-system
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: postgrespassword # default password for local use only
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: cnpg-system
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-auth
  storage:
    size: 2Gi
    storageClass: standard
  bootstrap:
    initdb:
      database: app
      owner: postgres
      secret:
        name: postgres-auth
  postgresql:
    parameters:
      log_connections: "on"
      log_disconnections: "on"
    pg_hba:
      - host all all all md5